NADOOIT/NADOO-Wiki

README.md

Bitte die Änderungen prüfen und anschließend mergen.

Ändere die Reihenfolge der Begrüßung im README und verbessererte Formatierung

---

README.md
docs/1/1/README.md
docs/1/2/README.md
docs/1/3/README.md
docs/1/4/REDME.md
docs/1/README.md

Aufteilung der README.md in verschiedene Dateien für die Kapitel und Unterkapitel

---

README.md
docs/1/1/README.md
docs/1/2/README.md
docs/1/3/README.md
docs/1/4/README.md
docs/1/5/README.md
docs/1/README.md
docs/2/1/README.md
docs/2/2/README.md
docs/2/3/README.md
docs/2/README.md
docs/3/1/README.md
docs/3/2/2/README.md
docs/3/2/3/README.md
docs/3/2/4/README.md
docs/3/2/5/README.md
docs/3/7/README.md
docs/4/README.md
docs/5/README.md
docs/6/README.md
docs/7/README.md
docs/8/README.md

@HibaAlanssari, @Kretta 
Ich habe die festgestellten Fehler mit diesem Branch aus dem Issue hoffentlich über den Pull request hier gelöst. 
Bitte Code-Review durchführen, damit wir die Verbesserungen in die Main übertragen können.

73 wiki einige links in der navigation des umgestellten wikis funktionieren nicht 779

---

docs/2/2/README.md

Corrected a typo in the README.md file to improve clarity.

Fix spelling error in README.md

---

docs/3/1/6/README.md
docs/3/1/7/README.md
docs/3/1/README.md

Include a new section in the documentation detailing how to effectively utilize GitHub's search feature, along with an updated link in the README.md for better navigation.
[806](https://github.com/NADOOIT/NADOO-Launchpad/issues/806)
@NADOOITChristophBa , @majdAlmotaem , @Abdel-213 , @Alexander-AzTech2064 , @HibaAlanssari , @CaptainCarsten , @Kretta , @IrinaZittlau , @jokerfip , @Flowdi  bitte nochmal die Code-Review üben.

[Neuer Eintrag]: 3.1.7 GitHub Suchfunktion effizient nutzen

---

README.md
docs/3/1/2/1/README.md

Branch Protection übertragen

---

README.md
docs/1/8/README.md

KAIZEN bei Christoph Backhaus IT

---

README.md
docs/3/10/README.md

KI‐Nutzung: Ein umfassender Leitfaden

---

README.md
docs/1/9/README.md

Die Verantwortung und Unsicherheit des Programmierer‐Daseins

---

README.md
docs/3/1/4/1/README.md

Issue Erstellungs Guide

---

README.md
docs/3/3/3/README.md

Speech‐to‐Text‐Feature im NADOO Launchpad

---

docs/1/2/4/README.md

Umgang mit Unternehmensdaten

---

docs/1/2/3/README.md
docs/1/2/4/README.md

1.2.3 Feiertag ergänzt und Formulierung aktualisiert.
1.2.4 Formulierung aktualisiert.
In beiden Fällen Rechtschreibung korrigiert.

Ergänzung und Korrektur

---

docs/1/1/README.md
docs/1/2/2/README.md

Anredeänderung in 2.Person Sg.
Zusätzlich: Relativpronomen in 1.2.2 korrigiert.

"globalyou"/"gerneperdu"

---

docs/1/4/README.md
docs/2/2/README.md

1.4.2 Komma vor Nebensatz
2.2 Satzbau/Grammatik

Korrekturen

---

docs/01-organisation/01-zeit-ausbildungsnachweise/01-beispiele/README.md
docs/01-organisation/01-zeit-ausbildungsnachweise/03-ueberpruefung/README.md
docs/01-organisation/01-zeit-ausbildungsnachweise/README.md
docs/01-organisation/04-krankmeldungen/README.md
docs/01-organisation/07-feedback-kultur/README.md
docs/01-organisation/09-jobrotation-weiterbildung/README.md
docs/01-organisation/10-teamkoordination/README.md
docs/01-organisation/11-vorbereitung-training/README.md
docs/01-organisation/12-kaizen/README.md
docs/02-tools/01-github/02-branches/01-protection/README.md

- Korrekturen
- Vereinheitlichung der persönlichen Anrede

Korrekturdurchsicht: 01-organisation

---

docs/02-tools/02-vscode/02-plugins/README.md
docs/02-tools/04-terminal/README.md
docs/02-tools/05-ki/02-gemini/README.md
docs/02-tools/05-ki/README.md

Fertigstellung der Korrekturdurchsicht von "02-tools".

Korrekturdurchsicht

---

docs/01-organisation/02-zeit_und_ausbildungsnachweise/03-ueberpruefung/README.md
docs/01-organisation/08-firmenphilosophie/01-verhaltensregeln/README.md
docs/02-arbeiten_bei_nadoo/01-rollen_und_aufgaben/05-teamkoordinator/README.md
docs/02-arbeiten_bei_nadoo/01-rollen_und_aufgaben/README.md
docs/02-arbeiten_bei_nadoo/02-training_und_vorbereitung/01-trainingsbeitraege/README.md
docs/02-arbeiten_bei_nadoo/02-training_und_vorbereitung/README.md

Nachkorrekturen:
- 01-organisation
- 02-arbeiten_bei_nadoo

Nachkorrekturen (01+02)

---

docs/03-meetings/02-11er/README.md
docs/03-meetings/README.md

- Minimale Korrekturen.
- Klärung: Breakout in 11er-Meeting? -> Wird ggf. innerhalb dieses Pull Requests korrigiert, wenn nötig.

Korrekturen / Klärung

---

docs/01-organisation/02-zeit_und_ausbildungsnachweise/README.md
docs/01-organisation/04-urlaub/README.md

- kurzes Step-by-Step im Abschnitt "Urlaubsregelungen" ergänzt

issue #387 | Ergänzung Urlaubsantrag stellen

---

docs/04-tools/03-intellij/01-installation/README.md
docs/04-tools/04-terminal/README.md

Korrekturdurchsicht -> "04-tools" -> "02-vscode" bis "05-ki"

---

docs/05-kommunikation/01-discord/01-einrichtung/README.md
docs/05-kommunikation/02-webcam/01-droidcam/README.md
docs/05-kommunikation/README.md

- Persönliche Anrede angepasst.
- Discord-Support-Unterpunkt konkretisiert: Klärung bzgl. Support-Kanal nötig. Zusätzlich wird im Nachgang ein Link zum zugehörigen Issue-Template eingefügt.

Nachkorrektur -> "05-kommunikation"

---

CODE_OF_CONDUCT.md

Introduce a code of conduct to foster a respectful and productive environment within the NADOO-IT community, along with minor formatting corrections in the introduction.

Add code of conduct for NADOO-IT community

---

docs/06-entwicklung/05-python/01-debugging/README.md
docs/06-entwicklung/05-python/02-briefcase-toga/01-debugging/README.md
docs/06-entwicklung/05-python/02-briefcase-toga/02-launchpad/README.md
docs/06-entwicklung/05-python/02-briefcase-toga/03-speech-to-text/README.md
docs/06-entwicklung/05-python/02-briefcase-toga/README.md
docs/06-entwicklung/05-python/README.md

Anrede angepasst.
Fehler korrigiert.
@Monika32025 und @TimHellmig: Nach finaler Durchsicht gerne mergen. Lieben Dank. 😊

Korrektur: "06-entwicklung" -> "01-dokumentation" bis "05-python"

---

docs/01-organisation/02-zeit_und_ausbildungsnachweise/02-dateibenennung/README.md
docs/05-kommunikation/01-discord/01-einrichtung/README.md
docs/06-entwicklung/07-eigene_app/README.md
docs/06-entwicklung/08-lizenzen_open_source/README.md

- Anrede angepasst.
- Minimale Korrekturen.
- Konkretisierung von "kw" -> #443
- Entfernung von Code-Kommentar im Discord-Abschnitt, da Verlinkung bereits vorhanden.

Korrekturdurchsicht -> "06-entwicklung" (übrige)

---

docs/05-kommunikation/01-discord/01-einrichtung/README.md
docs/05-kommunikation/01-discord/README.md
docs/05-kommunikation/02-webcam/01-droidcam/README.md
docs/05-kommunikation/02-webcam/02-ios/README.md
docs/05-kommunikation/02-webcam/README.md
docs/05-kommunikation/README.md

- Überschriften korrigiert, wo notwendig + zentriert
- Navigationsbar / Pfad-Verlinkungen korrigiert oder hinzugefügt

[#374][Branch 5] 05-kommunikation

---

README.md
docs/03-meetings/01-allgemein-morgens/README.md
docs/03-meetings/02-11er/README.md
docs/03-meetings/03-teamkoordination/README.md
docs/03-meetings/04-33er/README.md
docs/03-meetings/README.md

- Überschriften zentriert
- Navigationsbar / Pfad-Verlinkungen korrigiert oder hinzugefügt

[#374][Branch 3] 03-meetings

---

README.md
docs/07-methoden_und_projekte/01-projektmanagement/01-zeitmanagement/README.md
docs/07-methoden_und_projekte/01-projektmanagement/02-planung/01-antrag/README.md
docs/07-methoden_und_projekte/01-projektmanagement/02-planung/README.md
docs/07-methoden_und_projekte/01-projektmanagement/03-projektmanagement/README.md
docs/07-methoden_und_projekte/01-projektmanagement/04-phasen/README.md
docs/07-methoden_und_projekte/01-projektmanagement/05-abschlussprojekt/README.md
docs/07-methoden_und_projekte/01-projektmanagement/README.md
docs/07-methoden_und_projekte/02-methoden/01-scrum/README.md
docs/07-methoden_und_projekte/02-methoden/02-kanban/README.md
docs/07-methoden_und_projekte/02-methoden/README.md
docs/07-methoden_und_projekte/README.md

- Überschriften korrigiert, wo notwendig und zentriert
- Navigationsbar / Pfad-Verlinkungen korrigiert oder hinzugefügt

[#374][Branch 7] 07-methoden_und_projekte

---

README.md
docs/06-entwicklung/01-dokumentation/README.md
docs/06-entwicklung/02-clean_architecture/01-praxisbeispiel/README.md
docs/06-entwicklung/02-clean_architecture/02-best_practices/README.md
docs/06-entwicklung/02-clean_architecture/README.md
docs/06-entwicklung/03-lizenzen_und_opensource/README.md
docs/06-entwicklung/04-python/01-einstieg/01-virtuelle_umgebungen/README.md
docs/06-entwicklung/04-python/01-einstieg/02-installation/README.md
docs/06-entwicklung/04-python/01-einstieg/03-grundkonzept_bsp/README.md
docs/06-entwicklung/04-python/01-einstieg/README.md
docs/06-entwicklung/04-python/02-debugging/README.md
docs/06-entwicklung/04-python/README.md
docs/06-entwicklung/05-java/README.md
docs/06-entwicklung/06-frameworks/01-nadoo_framework/README.md
docs/06-entwicklung/06-frameworks/02-briefcase_und_toga/01-briefcase/README.md
docs/06-entwicklung/06-frameworks/02-briefcase_und_toga/02-toga/README.md
docs/06-entwicklung/06-frameworks/02-briefcase_und_toga/03-zusammenspiel/README.md
docs/06-entwicklung/06-frameworks/02-briefcase_und_toga/04-debugging/README.md
docs/06-entwicklung/06-frameworks/02-briefcase_und_toga/README.md
docs/06-entwicklung/06-frameworks/README.md
docs/06-entwicklung/07-digitale_produktentwicklung/01-idee_und_vorbereitung/README.md
docs/06-entwicklung/07-digitale_produktentwicklung/02-umsetzung/README.md
docs/06-entwicklung/07-digitale_produktentwicklung/03-feedback_und_testing/README.md
docs/06-entwicklung/07-digitale_produktentwicklung/README.md
docs/06-entwicklung/README.md

- Überschriften korrigiert, wo notwendig bzw. zentriert
- Navigationsbar / Pfad-Verlinkungen korrigiert oder hinzugefügt

[#374][Branch 6] 06-entwicklung

---

docs/03-meetings/03-teamkoordination/README.md

Siehe auch https://github.com/NADOOIT/NADOO-Launchpad/issues/1467

Aktualisiere README.md: Ergänze Dokumentationshinweis und strukturiere die Agenda

---

docs/00-willkommen/01-leitfaden/README.md

Discord-Channel-Name wurde angepasst.

Anpassen des richtigen Discord-Chanel Namens im Wiki

---

docs/04-tools/05-launchpad/02-features/02-berechtigungen/README.md
docs/04-tools/05-launchpad/02-features/03-tokens/README.md
docs/04-tools/05-launchpad/02-features/04-zeiterfassung/README.md

Die Verlinkungen der Dateien angepasst.
Diese hatten zuvor nicht mehr funktioniert und sind nun funktionsfähig.

Feinschliff

---

docs/00-willkommen/01-leitfaden/README.md
docs/04-tools/04-terminal/README.md

Textinhalt verschoben

---

docs/05-kommunikation/03-bekannte_Probleme/README.md

created new section and known issues in Discord to read up on

new section for bekannte Probleme

---

docs/01-organisation/01-zeiterfassung/README.md
docs/01-organisation/02-zeit_und_ausbildungsnachweise/01-beispiele/README.md

Update Zeit Erfassung & Nachweis (Teil von #547).
Änderungen:
- docs/01-organisation/01-zeiterfassung/README.md — Regeln für Stempeln + E-Mail-Betreff 
- docs/01-organisation/02-zeit_und_ausbildungsnachweise/README.md — E-Mail-Vorlage + Dateinamen + Beispiele

docs: Update Zeiterfassung & Nachweise (Issue #547)

---

docs/01-organisation/03-arbeits_und_pausenzeiten/README.md

temporarily time tracking with email

updating the time tracking process

---

docs/02-arbeiten_bei_nadoo/README.md

links on topic overview updated

fixed links on topic overview

---

docs/01-organisation/02-zeiterfassung/README.md

Die Beschreibung der Zeiterfassung wurde auf das aktuelle Anmeldemodell angepasst.
Bilder wurden entfernt und im nachhinein als aktualisierte Variante eingefügt.

Zeiterfassung aktualisiert

---

README.md

alle Verlinkungen zu dem Ordner Windsurf hinzugefügt und alle nachfolgenden Verlinkungen angepasst

Verlinkung zu der Seite Windsurf hinzugefügt

---

docs/04-tools/03-intellij/02-installation/README.md

Die Bilder wurden nicht mehr erkannt, da der Ersteller, diese aus einer nicht mehr verfügbaren Quelle zur Verfügung gestellt hat. 
Neue Bilder werden im Nachhinein in die Main eingefügt.
Pfad: docs/04-tools/03-intellij/02-installation/README.md

Bilder akutalisieren

---

docs/00-willkommen/02-starterpack/README.md

Windsurf und Link zur Readme von dem Order Windsurf wurden der Liste des Starterpacks hinzugefügt unter dem Punkt: **Tools und Programme im täglichen Arbeitsgebrauch.**
Pfad: docs/00-willkommen/02-starterpack/README.md

Windsurf zur Liste des Starterpacks hinzugefügt

---

docs/06-entwicklung/README.md

Pfad: **docs/05-kommunikation/03-bekannte_Probleme**
Ordnername von 03-bekannte_**P**robleme geändert in 03-bekannte_**p**robleme. (P = klein statt groß)
Neue Zeile hinzugefügt um Branch zu schließen.

Änderung Ordnername
